# AUTOGENERATED FILE
FROM #{FROM}

# A few problems with compiling Java from source:
#  1. Oracle.  Licensing prevents us from redistributing the official JDK.
#  2. Compiling OpenJDK also requires the JDK to be installed, and it gets
#       really hairy.

RUN apt-get update && apt-get install -y --no-install-recommends \
		bzip2 \
		unzip \
		xz-utils \
	&& rm -rf /var/lib/apt/lists/

#{ADD_SUITE}

# Default to UTF-8 file.encoding
ENV LANG C.UTF-8

# add a simple script that can auto-detect the appropriate JAVA_HOME value
# based on whether the JDK or only the JRE is installed
RUN { \
		echo '#!/bin/sh'; \
		echo 'set -e'; \
		echo; \
		echo 'dirname "$(dirname "$(readlink -f "$(which javac || which java)")")"'; \
	} > /usr/local/bin/docker-java-home \
	&& chmod +x /usr/local/bin/docker-java-home

ENV JAVA_HOME #{JAVA_HOME}

ENV JAVA_VERSION #{FULL_VERSION}
ENV JAVA_DEBIAN_VERSION #{DEBIAN_VERSION}

#{CA_HACK0}

RUN set -x \
	&& apt-get update \
	&& apt-get install -y #{DEBIAN_PRIORITIZED_SOURCE} \
		#{DEBIAN_PACKAGE}="$JAVA_DEBIAN_VERSION" \
	#{CA_HACK1}&& rm -rf /var/lib/apt/lists/* \
	&& [ "$JAVA_HOME" = "$(docker-java-home)" ]

#{CA_HACK2}

CMD ["echo","'No CMD command was set in Dockerfile! Details about CMD command could be found in Dockerfile Guide section in our Docs. Here's the link: http://docs.resin.io/deployment/dockerfile"]
