# AUTOGENERATED FILE
FROM #{FROM}

#{ARCH=ARM} RUN [ "cross-build-start" ]

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl libunwind8 gettext icu-devtools && \
    rm -rf /tmp/* /var/tmp/* && \
    rm -rf /var/lib/apt/lists/* && \
    rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin

WORKDIR /tmp

RUN curl -sSL -o #{DOTNET_BUNDLE_BASENAME} #{DOTNET_BUNDLE} && \
    echo "#{DOTNET_BUNDLE_SHA256SUM}" | sha256sum -c - || true && \
    mkdir -p /opt/dotnet && \
    tar zxf #{DOTNET_BUNDLE_BASENAME} -C /opt/dotnet && \
    ln -s /opt/dotnet/dotnet /usr/local/bin && \
    rm -rf /tmp/*

ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false \
    LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8

# Enable correct mode for dotnet watch (only mode supported in a container)
ENV DOTNET_USE_POLLING_FILE_WATCHER=true \
    # Skip extraction of XML docs - generally not useful within an image/container - helps perfomance
    NUGET_XMLDOC_MODE=skip

#{ARCH=ARM} RUN [ "cross-build-end" ]

WORKDIR /app

CMD [ "dotnet", "--help" ]
