name: "Autogenerate"
description: "Download and push libraries"
inputs:
  json:
    description: "JSON stringified object containing all the inputs from the calling workflow"
    required: true
  secrets:
    description: "JSON stringified object containing all the secrets from the calling workflow"
    required: true
  variables:
    description: "JSON stringified object containing all the variables from the calling workflow"
    required: true

runs:
  using: "composite"
  steps:
    # https://github.com/dawidd6/action-download-artifact
    - name: Download patches from PR workflow
      id: download_patches
      continue-on-error: true
      uses: dawidd6/action-download-artifact@268677152d06ba59fcec7a7f0b5d961b6ccd7e1e # v2.28.0
      with:
        github_token: ${{ fromJSON(inputs.secrets).GITHUB_TOKEN }}
        commit: ${{ github.event.pull_request.head.sha || github.event.head_commit.id }}
        path: ${{ runner.temp }}/patches
        workflow_conclusion: success
        name: patches-${{ github.event.pull_request.head.sha }}

    # We need a token with contents:write and workflows:write permissions
    # so the automatic GITHUB_TOKEN won't work
    # https://github.com/tibdex/github-app-token
    - name: Generate GitHub App installation token
      if: steps.download_patches.outcome == 'success'
      uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
      id: gh_app_token
      with:
        app_id: "400994"
        installation_retrieval_mode: organization
        installation_retrieval_payload: ${{ github.event.repository.owner.login }}
        private_key: ${{ fromJSON(inputs.secrets).BALENALIB_BOT_PRIVATE_KEY }}
        repositories: >
          ["${{ github.event.repository.name }}"]

    # The cached credentials in the existing checkout don't have
    # the permissions we need to push to the repo
    # https://github.com/actions/checkout
    - name: Checkout code
      if: steps.download_patches.outcome == 'success'
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      with:
        fetch-depth: 1
        token: ${{ steps.gh_app_token.outputs.token }}
        ref: ${{ github.ref }}
        persist-credentials: false
        path: ${{ github.ref }}

    - name: Apply patches
      if: steps.download_patches.outcome == 'success'
      working-directory: ${{ github.ref }}
      shell: bash
      env:
        # get the user id of the GitHub App
        # gh api /users/balenalib-workflows%5Bbot%5D
        GIT_AUTHOR_NAME: balenalib-workflows[bot]
        GIT_AUTHOR_EMAIL: 146760701+balenalib-workflows[bot]@users.noreply.github.com
        GIT_COMMITTER_NAME: balenalib-workflows[bot]
        GIT_COMMITTER_EMAIL: 146760701+balenalib-workflows[bot]@users.noreply.github.com
      run: |
        git am -q ${{ runner.temp }}/patches/*.patch

    # https://github.com/ad-m/github-push-action
    - name: Push changes
      uses: ad-m/github-push-action@d91a481090679876dfc4178fef17f286781251df # v0.8.0
      if: steps.download_patches.outcome == 'success'
      with:
        github_token: ${{ steps.gh_app_token.outputs.token }}
        branch: ${{ github.ref }}
        directory: ${{ github.ref }}
        force_with_lease: true
