FROM resin/raspberry-pi-buildpack-deps:wheezy-scm

RUN apt-get update && apt-get install -y \
		autoconf \
		build-essential \		
		i2c-tools \
		imagemagick \
		iputils-ping \	
		ifupdown \	
		less \
		libbz2-dev \
		libcurl4-openssl-dev \
		libevent-dev \
		libffi-dev \
		libglib2.0-dev \
		libjpeg-dev \
		libmagickcore-dev \
		libmagickwand-dev \
		libmysqlclient-dev \
		libncurses-dev \
		libpq-dev \
		libraspberrypi-bin \
		libreadline-dev \
		libsqlite3-dev \
		libssl-dev \
		libxml2-dev \
		libxslt-dev \
		libyaml-dev \
		module-init-tools \
		nano \
		net-tools \
		zlib1g-dev \
		usbutils \		
	&& rm -rf /var/lib/apt/lists/*
