#!/bin/bash

set -e

usage() {
    cat <<EOUSAGE
A small script that runs an idle process to keep the container running, while periodically printing the log: "Idling..."

Options:
  --message    Message to print when ilding (Default to "Idling...").
  --interval   Printing interval in second (Default to 600 seconds).
  --silent     No idle message.

EOUSAGE
}

message="Idling..."
interval=600
is_silent=

# Args handling
opts="$(getopt -o 'h?' --long 'message:,interval:,silent' -- "$@" || { usage >&2 && exit 1; })"
eval set -- "$opts"

while true; do
    flag=$1
    shift
    case "$flag" in
        --message) message="$1" && shift ;;
        --interval) interval="$1" && shift ;;
        --silent) is_silent=true ;;
        --) break ;;
        *)
            {
                echo "error: unknown flag: $flag"
                usage
            } >&2
            exit 1
            ;;
    esac
done

if [ "$is_silent" == true ] ; then
    sleep infinity
else
    while : ; do echo "$message"; sleep $interval; done
fi
