name: bake

"on":
  workflow_dispatch:
    inputs:
      no-push:
        description: Do not push to DockerHub
        required: false
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare matrix
    runs-on: ubuntu-latest

    outputs:
      bake-targets: ${{ steps.bake-targets.outputs.matrix }}

    steps:

      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
        with:
          fetch-depth: 1

      - name: Set matrix
        id: bake-targets
        run: |
          set -x
          targets="$(jq -cr '.group.default.targets' $LIBRARY)"
          echo "matrix=$targets" >> $GITHUB_OUTPUT

  bake:
    name: Bake images
    runs-on: ubuntu-latest
    # timeout-minutes: 480
    needs:
      - prepare

    strategy:
      # max-parallel: 20
      fail-fast: false
      matrix:
        target: ${{ fromJSON(needs.prepare.outputs.bake-targets) }}

    steps:

      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
        with:
          fetch-depth: 1

      # https://github.com/docker/setup-qemu-action
      - name: Setup QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3
        with:
          platforms: all
          # https://hub.docker.com/r/tonistiigi/binfmt
          image: tonistiigi/binfmt:qemu-v6.2.0

      # https://github.com/docker/setup-buildx-action
      - name: Setup buildx
        uses: docker/setup-buildx-action@2b51285047da1547ffb1b2203d8be4c0af6b1f20 # v3
        with:
          driver-opts: network=host
          install: true

      # https://github.com/docker/login-action
      - name: Login to DockerHub
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3
        if: inputs.no-push != true
        with:
          registry: docker.io
          username: ${{ secrets.BALENAIMAGES_USER }}
          password: ${{ secrets.BALENAIMAGES_TOKEN }}

      # https://github.com/docker/bake-action
      - name: Docker bake
        continue-on-error: false
        id: docker_bake
        uses: docker/bake-action@017aa056d6bfc9797de5a5dd354a209dc07b490e # v4
        with:
          workdir: balena-base-images
          files: ${{ github.workspace }}/${{ env.LIBRARY }}
          targets: ${{ matrix.target }}
          push: ${{ inputs.no-push != true }}
          provenance: false
