name: Bake all
'on':
  workflow_dispatch:
    inputs:
      cancel-in-progress:
        description: Cancel all in-progress bake workflows and do not start any new ones
        required: false
        type: boolean
        default: false

# A single bake workflow can generate hundreds of jobs once the matrixes are
# expanded, so they are limited the same concurrency group even though
# they are of different architectures and device types.
# Do not cancel in-progress as we are expecting multiple bake workflows listening
# for this event and we don't want them to cancel each other.
concurrency:
  group: bake
  cancel-in-progress: ${{ inputs.cancel-in-progress == true }}

# Downstream bake workflows are listening for 'Bake all' workflow_run completed events but
# they will be skipped if the condition github.event.workflow_run.conclusion != 'success'.
jobs:
  do-success:
    name: Return success
    runs-on: ubuntu-latest
    if: ${{ inputs.cancel-in-progress != true }}
    steps:
      - run: exit 0
